### ISSUE TITLE
Readme not clear enough 

### ISSUE THREAD

**Issue by rohanagarwal94** [blocknotary/ethernote#2]
I am new to the Blockchain technology. Therefore I suggest the author to update the readme including every step that needs to be done in order to install the program such as running the RPC client for respective operating system and how to start it on a particular port.

**Comment by garyrianto** [comment]
I agree with Rohanagarwal94, a bit more explanation on every step that needs to be done would be convenient.

**Comment by igorbarinov** [comment]
Ok guys, we will add it tomorrow
@vbaranov
