### ISSUE TITLE
Inaccessible host : AWS?

### ISSUE THREAD

**Issue by Koennavaro** [blocknotary/ethernote#3]
Hello, 

I got the following error message after filling in the contract and pressing the button Accept: 

Inaccessible host: `s3.aws_region.amazonaws.com'. This service may not be available in the `AWS_region' region.

Do we need to fill in the AWS fields in the config.js ? We tried to fill it in with our own AWS account, but we still got the same error.

**Comment by rohanagarwal94** [comment]
@Koennavaro try to fill in the region code of the area in the region. Check the AWS website for the region codes.

**Comment by vbaranov** [comment]
Hi,
Yes, you should.
Please, check updated [README.md](https://github.com/blocknotary/ethernote/blob/master/README.md) with extended description.
Please, also check the [list of available regions for AWS S3](http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region)
